version: "3.9"

x-defaults:
  environment: &enviroment_defaults
    DEBUG: "True"
    PRETIX_API: http://tickets.pycon.it/api/v1/
    PRETIX_API_TOKEN: None # ask for a token
    SECRET_KEY: secret-key
    SLACK_INCOMING_WEBHOOK_URL: None
    STRIPE_SECRET_API_KEY: None # Ask if you need it
    STRIPE_SUBSCRIPTION_PRICE_ID: price_1IkVzxD5MZ3GejSORRBZCvK6
    STRIPE_WEBHOOK_SIGNATURE_SECRET: None
    PASTAPORTO_SECRET: pastaporto-secret
    ASSOCIATION_FRONTEND_URL: http://localhost:3020

services:
  pycon-backend:
    build: ./backend
    networks: [pycon_net]
    entrypoint: ""
    command: sh -c "python manage.py create_admin &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    tty: true
    stdin_open: true
    ports:
      - 8000:8000
    volumes:
      - ./backend:/home/app/
    environment:
      <<: *enviroment_defaults
      DATABASE_URL: psql://pycon:pycon@pycon-backend-db/pycon
      DJANGO_SETTINGS_MODULE: pycon.settings.dev
    depends_on:
      - pycon-backend-db

  pycon-backend-db:
    image: postgres:11.10
    networks: [pycon_net]
    environment:
      POSTGRES_USER: pycon
      POSTGRES_PASSWORD: pycon
      POSTGRES_DB: pycon

networks:
  pycon_net:
