# hi
[build]
    base    = "frontend"


[[redirects]]
    from = "/admin/*"
    to = "https://d1111jewijk23m.cloudfront.net/admin/:splat"
    status = 200
    force = true

[[redirects]]
    from = "/django-static/*"
    to = "https://d1111jewijk23m.cloudfront.net/django-static/:splat"
    status = 200
    force = true

[[redirects]]
    from = "/media/*"
    to = "https://d1111jewijk23m.cloudfront.net/media/:splat"
    status = 200
    force = true

[[redirects]]
    from = "/graphql"
    to = "https://d1111jewijk23m.cloudfront.net/graphql"
    status = 200
    force = true

[[redirects]]
    from = "/"
    to = "/it"
    status = 301
    force = false
    conditions = {Language = ["it"]}

[[redirects]]
    from = "/"
    to = "/en"
    status = 301
    force = false
