name: Backend tests

on:
  pull_request:
    paths:
    - 'backend/**/*'
    - 'backend/*'

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7.4'
      - run: pip install poetry
      - name: Install dependencies
        working-directory: backend
        run: poetry install
      - name: Install codecov
        working-directory: backend
        run: pip install codecov
      - name: pytest
        working-directory: backend
        run: |
            set +e
            OUTPUT=$(poetry run pytest --cov-report xml --cov=. --cov-fail-under 100)
            STATUS=$?
            echo "$OUTPUT"
            cd ..
            codecov
            exit $STATUS
        env:
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7.4'
      - run: pip install poetry
      - name: Install dependencies
        working-directory: backend
        run: poetry install
      - name: pytest
        working-directory: backend
        run: poetry run pytest --integration
        env:
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
