name: Deploy Pretix

on:
  push:
    branches:
      - master
    paths:
      - "pretix/**"

jobs:
  build-and-push-pretix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        working-directory: pretix
        run: docker build . --file Dockerfile --tag pythonitalia/pretix:latest
      - name: Publish the image
        working-directory: pretix
        run: docker push pythonitalia/pretix:latest

  deploy-to-eb:
    runs-on: ubuntu-latest
    needs: [build-and-push-pretix]

    steps:
      - uses: actions/checkout@master

      - name: eb deploy
        uses: ./.github/eb-action
        with:
          env: pretix
          args: deploy production-pretix --region eu-central-1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
