name: Slash Command Dispatch

on:
  issue_comment:
    types: [created]

jobs:
  slash-command-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.BOT_TOKEN }}
          reaction-token: ${{ secrets.BOT_TOKEN }}
          reaction-type: hooray
          permission: admin
          dispatch-type: workflow
          event-type-suffix: ""
          commands: |
            deploy
      - name: Edit comment with error message
        if: steps.scd.outputs.error-message
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.comment.id }}
          body: |
            > ${{ steps.scd.outputs.error-message }}
